### ISSUE TITLE
Sometimes on target image mouseleave lens won't hide.

### ISSUE THREAD

**Issue by payalord** [payalord/xZoom#9]
Sometimes on target image mouseleave event - lens won't hide. Or zoom not closed by some reason probably.

**Comment by procmail** [comment]
Hi, is this fix available in the release zip?

**Comment by payalord** [comment]
Hi, this issue isn't fixed yet. But i guess soon i'll review this.

**Comment by procmail** [comment]
Thanks and good to know. I will wait for the fix :)

**Comment by payalord** [comment]
Checked this issue, looks like this problem appears on jQuery/Javascript mouse event leave/out for many people in many other projects and not related to xZoom bug. I have tried all possible solutions for this bug, that has been recommended. Nothing worked yet. So if it is not possible to fix this native. Then for sure it is possible to find a workaround. So issue will be fixed anyway.

**Comment by Miloti** [comment]
Hi,
Has been solved this issue?
Thanks!

**Comment by payalord** [comment]
No, not yet. But it is possible to do some workaround with JS I think.

**Comment by Miloti** [comment]
I'm new with JS, maybe you can help me with some code :)
Thanks!

**Comment by payalord** [comment]
Ok, here is possible workaround solution for this:
```javascript
var xzoom = $('.xzoom, .xzoom-gallery').xzoom(); // <-- Your options here
var mobj = $('.xzoom:first');
var mw = mobj.width(), mh = mobj.height();

$(window).mousemove(function(event){
    var mx = event.pageX, my = event.pageY, moffset = mobj.offset(), mtop = moffset.top, mleft = moffset.left;
    if (mx < mleft || mx > mleft + mw || my < mtop || my > mtop + mh) xzoom.closezoom();
});
```

We adding mouse move event on window and checking for mouse move outside of the main image area. If detected, we telling zoom to close manually.

**Comment by Miloti** [comment]
Thank you for your code. I tested it, and I can see that the zoom closes. However, sometimes it still keeps showing after mouse move outside of the main image area. I'm testing this more but I'm not even sure if I'm calling your code properly. I'm able to show an alert message before this line:
   `    var mx = event.pageX, my = event.pageY, moffset = mobj.offset(), mtop = moffset.top, mleft = moffset.left;
` 
but not after it or inside the if statement :( I wounder how to check if the IF statement becomes True for some values and see some output result (text or whatever effect) or, in fact it becomes True but the alert function is not showing the result for some other reason.

This is what I put inside `<head>` element (please check the commented lines)

`<script type="text/javascript">

		var xzoom = $('.xzoom, .xzoom-gallery').xzoom(); // <-- Your options here
		var mobj = $('.xzoom:first');
		var mw = mobj.width(), mh = mobj.height();

		$(window).mousemove(function(event){
			alert("a");    // This guy is showing here
			var mx = event.pageX, my = event.pageY, moffset = mobj.offset(), mtop = moffset.top, mleft = moffset.left;
			alert("a");    // but not here!!
			if (mx < mleft || mx > mleft + mw || my < mtop || my > mtop + mh)
			{
				xzoom.closezoom();
				alert("Test");  //neither here!!
			}
		});
	</script>`

**Comment by payalord** [comment]
Which browser are you using (name/version)?

**Comment by payalord** [comment]
And what version of jQuery?

**Comment by Miloti** [comment]
I'm using Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
jQuery version 3.0.0

I'm testing in Mozilla Version 57.0.4 (64-bit) and so far it's working properly in Mozilla. 
I'm testing more :)

**Comment by payalord** [comment]
Let me create working tested example for you in sandbox. Just in a moment ok?

**Comment by Miloti** [comment]
ok I would be happy to see a working example :)

**Comment by payalord** [comment]
Check this example: https://github.com/payalord/xzoom-sandbox/tree/master/xZoomCloseIssue
I have tested this example on same version of Chrome and was able to put console.log("a"); that work fine, after that line you mentioned.

You better use console.log with devtools than alert function i think for debug.

**Comment by Miloti** [comment]
I have tested your example, after testing in Chrome, it still keeps showing the image after mouse move outside of the main image area [https://imgur.com/a/7d0VA](url)

Now I can play around with console.log("mx=" + mx) and I can see the values on mouse move and after mouse move outside of the main image area and this error appears:
Artikulli.php?id=7:57 Uncaught TypeError: Cannot read property 'closezoom' of undefined
    at Artikulli.php?id=7:57
    at dispatch (jquery.min.js:3)
    at q.handle (jquery.min.js:3)

You can check my test here [https://goo.gl/qTPnSP](url)

Right now I have this code in `<head>` element
`<script type="text/javascript">
	(function ($) {
		$(document).ready(function() {
			$(".xzoom, .xzoom-gallery").xzoom({zoomWidth: 550, zoomHeight: 500, lens: " #ffffff"});
			//Multiple Zooms on one page
			$('.xzoom').each(function() {
				var instance = $(this).xzoom(); //<-- Don't forget to add your options here
				$('.xzoom-gallery', $(this).parent()).each(function () {
					instance.xappend($(this));
				});
			});
		});
	})(jQuery);
	
		(function ($) {
    $(document).ready(function() {

        //Manual closing xzoom if mouse out of main image area, because sometimes jQuery 'mouseleave' event not working properly. 
        var xzoom = $('.xzoom, .xzoom-gallery').xzoom(); // <-- Your options here
        var mobj = $('.xzoom:first');
        var mw = mobj.width(), mh = mobj.height();

        $(window).mousemove(function(event){
            var mx = event.pageX, my = event.pageY, moffset = mobj.offset(), mtop = moffset.top, mleft = moffset.left;
			console.log("mx=" + mx)
            if (mx < mleft || mx > mleft + mw || my < mtop || my > mtop + mh)
			{
				xzoom.closezoom();
				 console.log("a")
			}				
        });

    });
})(jQuery);
	</script>`

**Comment by payalord** [comment]
I see what the problem now. Do you plan to use multiple zooms on one page? Or there will be only 1 zoom?

**Comment by Miloti** [comment]
Yes, I plan to have multiple zooms on one page.

**Comment by payalord** [comment]
Ok, then you need to change your whole script to this:
```javascript
<script type="text/javascript">
(function ($) {
  $(document).ready(function() {

    //Multiple Zooms on one page
    $('.xzoom').each(function() {

      //Initialization of xZoom here
      var instance = $(this).xzoom({zoomWidth: 550, zoomHeight: 500, lens: "#ffffff"}); //<-- Don't forget to add your options here

      $('.xzoom-gallery', $(this).parent()).each(function () {
        instance.xappend($(this));
      });

      var mobj = $(this);
      var mw = mobj.width(), mh = mobj.height();

      $(window).mousemove(function(event){
        var mx = event.pageX, my = event.pageY, moffset = mobj.offset(), mtop = moffset.top, mleft = moffset.left;
        if (mx < mleft || mx > mleft + mw || my < mtop || my > mtop + mh) instance.closezoom();
      });
    });

  });
})(jQuery);
</script>
```

I didn't tested it yet. So please check is it work for you or not. And let me know if any troubles.

**Comment by Miloti** [comment]
I tested this for 20 mins and no issue found :) If I find any problem I will let you know.
You did a great job :)
Thanks!

**Comment by poebrand** [comment]
Also, experiencing the same issue.

Work around helps but it appears there's a timing issue where the xremove method is not aware of the displayed elements.

**Comment by payalord** [comment]
I will close this issue, for timing problem if it will be required please open new issue with example and more details if possible. Thanks.
